# Generated by Django 4.1.7 on 2023-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola_mundo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='creado_el',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='modificado_el',
            field=models.DateField(auto_now=True),
        ),
    ]
